# Generated by Django 5.1.2 on 2024-10-25 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Developer Tool',
                'verbose_name_plural': 'Developer Tools',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='DjangoGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Django Guide',
                'verbose_name_plural': 'Django Guides',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='PythonTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Python Tutorial',
                'verbose_name_plural': 'Python Tutorials',
                'ordering': ['-date_added'],
            },
        ),
    ]
