# Generated by Django 5.1.2 on 2024-10-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_developertool_djangoguide_pythontutorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developertool',
            options={'verbose_name': 'Developer Tool', 'verbose_name_plural': 'Developer Tools'},
        ),
        migrations.AlterModelOptions(
            name='djangoguide',
            options={'verbose_name': 'Django Guide', 'verbose_name_plural': 'Django Guides'},
        ),
        migrations.AlterModelOptions(
            name='pythontutorial',
            options={'verbose_name': 'Python Tutorial', 'verbose_name_plural': 'Python Tutorials'},
        ),
        migrations.RemoveField(
            model_name='developertool',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='djangoguide',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='pythontutorial',
            name='date_added',
        ),
    ]
